---
- hosts: nginx
  become: yes

  tasks:
  - name: install nginx
    apt: name=nginx state=installed update_cache=yes

  - name: deploy website content
    git: repo=https://github.com/jweissig/episode-47.git
         dest=/usr/share/nginx/html/
         version=release-0.01

  - name: start ntp
    service: name=nginx state=started

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
